#!/bin/sh
sed -i "s#repository.engineering.redhat.com/nexus/repository/##g" packages/app/package-lock.json
sed -i "s#repository.engineering.redhat.com/nexus/repository/##g" packages/dev/package-lock.json
git add packages/app/package-lock.json
git add packages/dev/package-lock.json
