pcsd_integration_test:
  script:
    #
    #
    # install playwright dependencies
    #
    - dnf install -y
      alsa-lib-1.2.7.2-1.el9
      atk-2.36.0-5.el9
      at-spi2-atk-2.38.0-4.el9
      at-spi2-core-2.40.3-1.el9
      cairo-1.17.4-7.el9
      cups-libs-1:2.3.3op2-16.el9
      libdrm-2.4.111-1.el9
      libwayland-client-1.19.0-4.el9
      libX11-1.7.0-7.el9
      libxcb-1.13.1-9.el9
      libXcomposite-0.4.5-7.el9
      libXdamage-1.1.5-7.el9
      libXext-1.3.4-8.el9
      libXfixes-5.0.3-16.el9
      libxkbcommon-1.0.3-4.el9
      libXrandr-1.5.2-8.el9
      mesa-libgbm-22.1.5-2.el9
      pango-1.48.7-2.el9
    #
    #
    # install other dependencies
    #
    - dnf install -y
      npm
      cockpit-bridge
      fence-agents-all
    #
    #
    # install current version of pcs
    #
    - 'curl -Lk --output artifacts.zip --header "PRIVATE-TOKEN: ${PCS_REPO_TOKEN}" "${CI_API_V4_URL}/projects/pcs%2Fpcs/jobs/artifacts/main/download?job=rpm_build%3A%20%5BPcsRhel9CurrentRelease%5D"'
    - unzip artifacts.zip
    - "dnf install -y rpms/pcs-*.rpm"
    - rm -rf rpms/ artifacts.zip
    #
    #
    # build and install webui
    #
    - make init_nexus NEXUS_CERT_PATH="${NEXUS_CERT_PATH}"
    - make modules-prepare
    - make modules-patch
    - export BUILD_USE_CURRENT_NODE_MODULES=true
    #
    - export BUILD_DIR="$(pwd)"/build-standalone
    - make build
    - mv "$BUILD_DIR" /usr/lib64/pcsd/public/ui
    #
    - export BUILD_FOR_COCKPIT=true
    - export BUILD_DIR="$(pwd)"/build-cockpit
    - make build
    - mv "$BUILD_DIR" /usr/share/cockpit/ha-cluster
    #
    #
    # prepare environment for test (all)
    #
    - make test-modules-prepare
    - export PCSD_PROTOCOL_1=https
    - export PCSD_HOST_1=localhost
    - export PCSD_NODE_1=wuitest
    - export PCSD_USERNAME_1="hacluster"
    - export PCSD_PASSWORD_1=hh
    - export PCS_WUI_TESTS_HEADLESS=true
    - export PCS_WUI_TESTS_VIDEO_DIR=.test-records
    - export PCS_WUI_TEST_TIMEOUT=1000000
    - systemctl enable pcsd --now
    # hacluster user should already exists
    - echo "$PCSD_PASSWORD_1" | passwd "$PCSD_USERNAME_1" --stdin
    # tests expects that pcs is authenticated against the node
    - echo "127.0.0.1 $PCSD_NODE_1" >> /etc/hosts
    - pcs host auth "$PCSD_NODE_1" -u "$PCSD_USERNAME_1" -p "$PCSD_PASSWORD_1"
    - mkdir "$PCS_WUI_TESTS_VIDEO_DIR"
    - ln /var/log/pcsd/pcsd.log "$PCS_WUI_TESTS_VIDEO_DIR/pcsd.log"
    #
    #
    # test (standalone)
    #
    - export PCS_WUI_TEST_TYPE="standalone"
    - export PCSD_PORT_1=2224
    - make ci-cluster-test
    #
    #
    # test (cockpit)
    #
    - systemctl status cockpit
    - usermod --shell /bin/bash "$PCSD_USERNAME_1"
    - export PCS_WUI_TEST_TYPE="cockpit"
    - export PCSD_PORT_1=9090
    - make ci-cluster-test

  artifacts:
    when: on_failure
    paths:
      - .test-records/
    exclude:
      - node_modules/
      - .npmrc
    expire_in: 1 week
