pcsd_integration_test:
  script:
    # install playwright dependencies
    - dnf install -y
      alsa-lib-1.2.7.2-1.el9
      atk-2.36.0-5.el9
      at-spi2-atk-2.38.0-4.el9
      at-spi2-core-2.40.3-1.el9
      cairo-1.17.4-7.el9
      cups-libs-1:2.3.3op2-16.el9
      libdrm-2.4.111-1.el9
      libwayland-client-1.19.0-4.el9
      libX11-1.7.0-7.el9
      libxcb-1.13.1-9.el9
      libXcomposite-0.4.5-7.el9
      libXdamage-1.1.5-7.el9
      libXext-1.3.4-8.el9
      libXfixes-5.0.3-16.el9
      libxkbcommon-1.0.3-4.el9
      libXrandr-1.5.2-8.el9
      mesa-libgbm-22.1.5-2.el9
      pango-1.48.7-2.el9
    # install current version of pcs
    - 'curl -Lk --output artifacts.zip --header "PRIVATE-TOKEN: ${PCS_REPO_TOKEN}" "${CI_API_V4_URL}/projects/pcs%2Fpcs/jobs/artifacts/main/download?job=rpm_build"'
    - unzip artifacts.zip
    - "dnf install -y rpms/pcs-*.rpm"
    - rm -rf rpms/ artifacts.zip
    # build and install webui
    - make init_nexus NEXUS_CERT_PATH="${NEXUS_CERT_PATH}"
    - echo y | npx npm ci
    - echo y | .bin/patch-node-modules-for-fips.sh node_modules
    - echo y | make build BUILD_USE_EXISTING_NODE_MODULES=true
    - mv ./build /usr/lib64/pcsd/public/ui
    # run pcsd
    - systemctl enable pcsd --now
    # set hacluster password that the tests use
    - echo "hh"| passwd hacluster --stdin
    - pcs host auth localhost -u hacluster -p hh
    # run tests
    - mkdir .tmp
    - make testc TEST_CONFIG=.cluster-test-conf-gitlab.sh
  artifacts:
    when: on_failure
    paths:
      - .tmp/
    exclude:
      - node_modules/
      - .npmrc
    expire_in: 1 week
