/* eslint-disable @typescript-eslint/no-var-requires */
/* eslint-disable import/no-extraneous-dependencies */

// Do this as the first thing so that any code reading it knows the right env.
process.env.BABEL_ENV = "production";
process.env.NODE_ENV = "production";

// Makes the script crash on unhandled rejections instead of silently
// ignoring them. In the future, promise rejections that are not handled will
// terminate the Node.js process with a non-zero exit code.
process.on("unhandledRejection", err => {
  throw err;
});

// Ensure environment variables are read.
require("../config/env");

const bfj = require("bfj");
const webpack = require("webpack");

const paths = require("../config/paths");
const webpackConfig = require("../config/webpack.config");

const argv = process.argv.slice(2);
const writeStatsJson = argv.indexOf("--stats") !== -1;

const friendlySyntaxErrorLabel = "Syntax error:";

function isLikelyASyntaxError(message) {
  return message.indexOf(friendlySyntaxErrorLabel) !== -1;
}

const extractMessage = compilationMessage => {
  if (typeof compilationMessage === "string") {
    return compilationMessage;
  }
  if ("message" in compilationMessage) {
    return compilationMessage["message"];
  }
  if (Array.isArray(compilationMessage)) {
    return compilationMessage.find(m => "message" in m)?.message ?? "";
  }
  return "";
};

// https://github.com/webpack/webpack/blob/master/lib/ModuleError.js
const isWebpackAddedHeader = line => /Module [A-z ]+\(from/.test(line);

const transformParsingToSyntaxError = line => {
  const parsingErr = /Line (\d+):(?:(\d+):)?\s*Parsing error: (.+)$/.exec(line);
  if (!parsingErr) {
    return line;
  }
  const [, lineNumber, column, message] = parsingErr;
  return `${friendlySyntaxErrorLabel} ${message} (${lineNumber}:${column})`;
};

const syntaxError = [
  /SyntaxError\s+\((\d+):(\d+)\)\s*(.+?)\n/g, //(commonly found in CSS)
  `${friendlySyntaxErrorLabel} $3 ($1:$2)\n`,
];
const exportNotFound = [
  /^.*export '(.+?)' was not found in '(.+?)'.*$/gm,
  "Attempted import error: '$1' is not exported from '$2'.",
];
const defaultExportNotFound = [
  /^.*export 'default' \(imported as '(.+?)'\) was not found in '(.+?)'.*$/gm,
  "Attempted import error: '$2' does not contain a default export (imported as '$1').",
];
const importedExportNotFound = [
  /^.*export '(.+?)' \(imported as '(.+?)'\) was not found in '(.+?)'.*$/gm,
  "Attempted import error: '$1' is not exported from '$3' (imported as '$2').",
];
const internalStacks = [
  // Internal stacks are generally useless so we strip them... with the
  // exception of stacks containing `webpack:` because they're normally
  // from user code generated by webpack. For more information see
  // https://github.com/facebook/create-react-app/pull/1050
  /^\s*at\s((?!webpack:).)*:\d+:\d+[\s)]*(\n|$)/gm, // at ... ...:x:y
  "",
];
const anonymous = [/^\s*at\s<anonymous>(\n|$)/gm, ""]; // at <anonymous>

const cleanupWebpackMessage = compilationMessage =>
  extractMessage(compilationMessage)
    .split("\n")
    .filter(l => !isWebpackAddedHeader(l))
    .map(l => transformParsingToSyntaxError(l))
    .join("\n")
    .replace(...syntaxError)
    .replace(...exportNotFound)
    .replace(...defaultExportNotFound)
    .replace(...importedExportNotFound)
    .replace(...internalStacks)
    .replace(...anonymous)
    .trim();

function cleanupMessages({errors, warnings}) {
  const result = {
    errors: errors.map(cleanupWebpackMessage),
    warnings: (warnings || []).map(cleanupWebpackMessage),
  };
  if (result.errors.some(isLikelyASyntaxError)) {
    result.errors = result.errors.filter(isLikelyASyntaxError);
  }
  return result;
}

// Create the production build and print the deployment instructions.
function build() {
  console.log("Creating an optimized production build...");

  const compiler = webpack(
    webpackConfig({
      isProduction: true,
      isCockpitContext:
        process.env.REACT_APP_PCS_WEB_UI_ENVIRONMENT === "cockpit",
      // webpack needs to know it to put the right <script> hrefs into HTML even
      // in single-page apps that may serve index.html for nested URLs like
      // /todos/42. We can't use a relative path in HTML because we don't want
      // to load something like /todos/42/static/js/bundle.7289d.js. We have to
      // know the root.
      publicPath: "./",
      enableProfiling: process.argv.includes("--profile"),
    }),
  );
  return new Promise((resolve, reject) => {
    compiler.run((err, stats) => {
      let messages;
      if (err) {
        if (!err.message) {
          return reject(err);
        }

        let errMessage = err.message;

        // Add additional information for postcss errors
        if (Object.prototype.hasOwnProperty.call(err, "postcssNode")) {
          errMessage
            += "\nCompileError: Begins at CSS selector "
            + err["postcssNode"].selector;
        }

        messages = cleanupMessages({errors: [errMessage]});
      } else {
        messages = cleanupMessages(
          stats.toJson({all: false, warnings: true, errors: true}),
        );
      }
      if (messages.errors.length) {
        // Only keep the first error. Others are often indicative
        // of the same problem, but confuse the reader with noise.
        if (messages.errors.length > 1) {
          messages.errors.length = 1;
        }
        return reject(new Error(messages.errors.join("\n\n")));
      }

      const resolveArgs = {warnings: messages.warnings};

      if (writeStatsJson) {
        return bfj
          .write(paths.appBuild + "/bundle-stats.json", stats.toJson())
          .then(() => resolve(resolveArgs))
          .catch(error => reject(new Error(error)));
      }

      return resolve(resolveArgs);
    });
  });
}

build()
  .then(
    ({warnings}) => {
      if (warnings.length) {
        console.log(`Compiled with warnings.\n\n${warnings.join("\n\n")}`);
      } else {
        console.log("Compiled successfully.\n");
      }
    },
    err => {
      const tscCompileOnError = process.env.TSC_COMPILE_ON_ERROR === "true";
      if (tscCompileOnError) {
        console.log("Compiled with the following type errors:\n");
        console.log(err);
      } else {
        console.log("Failed to compile.\n");
        console.log(err);
        process.exit(1);
      }
    },
  )
  .catch(err => {
    if (err && err.message) {
      console.log(err.message);
    }
    process.exit(1);
  });
