export const FETCH_DASHBOARD_DATA = "/dashboard/FETCH_DASHBOARD_DATA";
export const FETCH_DASHBOARD_DATA_SUCCESS =
  "/dashboard/FETCH_DASHBOARD_DATA_SUCCESS"
;
export const FETCH_DASHBOARD_DATA_FAILED =
  "/dashboard/FETCH_DASHBOARD_DATA_FAILED"
;
