export const FETCH_CLUSTER_PROPERTIES = "/cluster-properties/FETCH_CLUSTER_PROPERTIES"
;
export const FETCH_CLUSTER_PROPERTIES_SUCCESS = "/cluster-properties/FETCH_CLUSTER_PROPERTIES_SUCCESS"
;
export const FETCH_CLUSTER_PROPERTIES_FAILED = "/cluster-properties/FETCH_CLUSTER_PROPERTIES_FAILED"
;
